# Generated by Django 4.2.4 on 2023-09-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaderboardmodel',
            options={'ordering': ['-points']},
        ),
        migrations.AlterField(
            model_name='sessionmodel',
            name='user_answer',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
