# Generated by Django 4.2.4 on 2023-09-01 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_leaderboardmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionmodel',
            name='user_answer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
